### ISSUE TITLE
Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by akarupt** [hamidsamak/pheditor#23]
jquery.js:3818 jQuery.Deferred exception: Cannot read property 'value' of undefined TypeError: Cannot read property 'value' of undefined
    at Function.Cl.fromTextArea (https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.43.0/codemirror.min.js:1:166888)
    at HTMLDocument.<anonymous> (https://cleancreations.com/why.php:149:25)
    at mightThrow (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:3534:29)
    at process (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:3602:12) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3818
jquery.js:3827 Uncaught TypeError: Cannot read property 'value' of undefined
    at Function.Cl.fromTextArea (codemirror.min.js:1)
    at HTMLDocument.<anonymous> (why.php:149)
    at mightThrow (jquery.js:3534)
    at process (jquery.js:3602)

**Comment by hamidsamak** [comment]
It seems your browser or internet connection is unable to access CDNJS or Cloudflare. Please check with another internet connection or proxy.
